apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octopusdb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: octopusdb
    server: {{ .Values.destination.server }}
  project: default
  source:
    path: bitnami/postgresql
    repoURL: https://charts.bitnami.com/bitnami
  syncPolicy:
    automated:
      prune: true
  helm:
    valueFiles:
      - helm-values/octopusdb.yaml
